feat(logs): introduce logback to have timestamp in the log file (#258)
Remove our custom trick and use logback to easily control how and what
we log
In addition, always use the 1.2.3 logback version

Note: the logback dependency is declared as 'compile' otherwise the integration
tests do not depend on it and NoClassDefFoundError is thrown